version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: passwordmanager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123!
      MYSQL_DATABASE: passwordmanager
      MYSQL_USER: pmuser
      MYSQL_PASSWORD: StrongPass123!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: passwordmanager-server
    restart: always
    env_file:
      - ./server/.env.docker
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./client-new #./client              
      dockerfile: Dockerfile
    container_name: passwordmanager-frontend
    restart: always
    ports:
      - "5173:5173"          
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    container_name: passwordmanager-nginx
    restart: always
    depends_on:
      - frontend
      - server
    ports:
      - "8080:80"   # נכנסים דרך http://localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  

volumes:
  db_data:
